import React from 'react';

const TitleSections = () => {
    return (
        <div className='container'>
            <div className='mb-[42px]'>
                <img src="/images/treeimg.png" alt="" />
            </div>
            <div className='border mb-[32px] border-gray-300 p-[40px]'>
                <h1 className='text-normal mb-[20px] font-medium'>1.1  Titile gose to here</h1>
                <p>
                    Infomaniak offsets 200% of the CO2 emissions generated by the company, including for example: the manufacture and disposal (recycling) of servers, the production of electricity (even renewable), the transport of employees to get to their place of work as well as the flights by plane which are necessary in the professional context.
                </p>
                <p className='my-[16px]'>

                    Infomaniak offsets 200% of the CO2 <span className='font-medium '>MyClimate</span>
                </p>
                <p>
                    Infomaniak offsets 200% of the CO2 emissions generated by the company, including for example: the manufacture and disposal (recycling) of servers, the production of electricity (even renewable), the transport of employees to get to their place of work as well as the flights by plane which are necessary in the professional context.
                </p>

            </div>
            <div className='border mb-[32px] border-gray-300 p-[40px]'>
                <h1 className='text-normal mb-[20px] font-medium'>1.2  Titile gose to here</h1>
                <p>
                    Infomaniak offsets 200% of the CO2 emissions generated by the company, including for example: the manufacture and disposal (recycling) of servers, the production of electricity (even renewable), the transport of employees to get to their place of work as well as the flights by plane which are necessary in the professional context.
                </p>
                <p className='my-[16px]'>

                    Infomaniak offsets 200% of the CO2 <span className='font-medium '>MyClimate</span>
                </p>
                <p>
                    Infomaniak offsets 200% of the CO2 emissions generated by the company, including for example: the manufacture and disposal (recycling) of servers, the production of electricity (even renewable), the transport of employees to get to their place of work as well as the flights by plane which are necessary in the professional context.
                </p>

            </div>
            <div className='border mb-[32px] border-gray-300 p-[40px]'>
                <h1 className='text-normal mb-[20px] font-medium'>1.3  Titile gose to here</h1>
                <p>
                    Infomaniak offsets 200% of the CO2 emissions generated by the company, including for example: the manufacture and disposal (recycling) of servers, the production of electricity (even renewable), the transport of employees to get to their place of work as well as the flights by plane which are necessary in the professional context.
                </p>
                <p className='my-[16px]'>

                    Infomaniak offsets 200% of the CO2 <span className='font-medium '>MyClimate</span>
                </p>
                <p>
                    Infomaniak offsets 200% of the CO2 emissions generated by the company, including for example: the manufacture and disposal (recycling) of servers, the production of electricity (even renewable), the transport of employees to get to their place of work as well as the flights by plane which are necessary in the professional context.
                </p>

            </div>

        </div >
    );
};

export default TitleSections;